[package]
name = "magneto"
version = "0.1.0"
authors = ["psr31"]
edition = "2018"

[dependencies]
wgpu = "0.8.1"
winit = "0.25.0"
bytemuck = { version = "1.7.0", features = ["derive"] }
image = "0.23"
anyhow = "1.0.41"
nalgebra = "0.27.1"
tobj = "3.0.1"
genmesh = "0.6.2"
log = "0.4.14"